version: '3'

services:
  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"

  customerservices:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"

  productservices:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:80"