version: '3'

services:

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - apigateway
    restart: always
    environment:
      DOMAINS: 'services.vip.com -> http://apigateway, auth.vip.com -> http://identityservices'
      STAGE: 'local'
      FORCE_RENEW: 'true'

  customerservices:
    image: vip/customerservices
    build:
      context: ./src/CustomerServices
      dockerfile: Dockerfile
    depends_on:
      - identityservices

  productservices:
    image: vip/productservices
    build:
      context: ./src/ProductServices
      dockerfile: Dockerfile
    depends_on:
      - identityservices

  apigateway:
    image: vip/gateway
    build:
      context: ./src/ApiGateway
      dockerfile: Dockerfile

  identityservices:
    image: identityservices
    build:
      context: ./src/IdentityServices
      dockerfile: Dockerfile
    depends_on:
      - sql.data

  sql.data:
    image: microsoft/mssql-server-linux:2017-latest